{% set version = "2.0.1" %}

package:
  name: qtpy
  version: {{ version }}

source:
  fn: qtpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{ version }}.tar.gz
  sha256: adfd073ffbd2de81dc7aaa0b983499ef5c59c96adcfdcc9dea60d42ca885eb8f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - packaging

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_file: LICENSE.txt
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

extra:
  recipe-maintainers:
    - ccordoba12
    - astrofrog-conda-forge
    - dalthviz
