{% set version = "2.3.0" %}

package:
  name: qtpy
  version: {{ version }}

source:
  fn: qtpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{ version }}.tar.gz
  sha256: 0603c9c83ccc035a4717a12908bf6bc6cb22509827ea2ec0e94c2da7c9ed57c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - pip
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - packaging

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_file: LICENSE.txt
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - ccordoba12
    - astrofrog-conda-forge
    - dalthviz
