{% set version = "2.3.1" %}

package:
  name: qtpy
  version: {{ version }}

source:
  fn: qtpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{ version }}.tar.gz
  sha256: a8c74982d6d172ce124d80cafd39653df78989683f760f2281ba91a6e7b9de8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - pip
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - packaging

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_file: LICENSE.txt
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - ccordoba12
    - astrofrog-conda-forge
    - dalthviz
