{% set version = "1.11.0" %}

package:
  name: qtpy
  version: {{ version }}

source:
  fn: qtpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{ version }}.tar.gz
  sha256: bbd61f8d6480a01cec39ad94249dbde7d0a8fce2aca61ff5037b645c4fd13e02

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_file: LICENSE.txt
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

extra:
  recipe-maintainers:
    - ccordoba12
    - astrofrog-conda-forge
    - Nodd
    - dalthviz
