{% set version = "1.10.0" %}

package:
  name: qtpy
  version: {{ version }}

source:
  fn: qtpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{ version }}.tar.gz
  sha256: 3d20f010caa3b2c04835d6a2f66f8873b041bdaf7a76085c2a0d7890cdd65ea9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_file: LICENSE.txt
  summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase

extra:
  recipe-maintainers:
    - ccordoba12
    - astrofrog-conda-forge
    - Nodd
