travis:
  secure:
    BINSTAR_TOKEN: YWPHynldufnf3pJjUoIgGv5oRXlVnTUmGUQFrikObBmf85tIP9SC0+jc14VoDINGVWIbnSsfC9jwoB0rElI1LggIToFI2AXuJ4cmNNBwt7BAFflL+qJ9ykZTvw/i6NbWrub120rw3qeGfYmSIhdvqlPYppP9eUR9LICc0FZwcmaBrPAYBhPoSDKIdzc0wM+82uiHN65Gmm4/lc+wD6RfOshoRtGJERXLw+OBRHEWekGRc6jZOgNXaCl9Dv3mi2kvEPejUaUB4BnU7jvf1U1/+s6MSRvHdkv2QQDjes1ylWKUEtrsfv+edhai90mjsJ1RKoNoo10tySOzoP0ME+F0/62GLZ+qFxIlmUhD5xr8TuoKcPVN+UD32pGfAae3XqbuxGXQoE4K1uhUyEyloXLBqOVpoufSUFFdhDxjSURU0Vd1cTnQpdFGkRzivAMvjvjwX6sv6iQVjiusuURoR+PAA3Gt6ay2LMHMn0Zy91/K8tVGvUo3Dtm5m15cnosVHU0FTwWAbkCNM3UvDBqXIEhOACQ6p/dYXsZYgcL2HzqTF1oFhetAWGzw7uVsCV6y5V7j8iR83YA2tnAt9yIIQ0I8NnRQcTN19NAmG0TyUttRYPN8anGoT+S8M30JNUeW1gsJKN+8r5nEEdoDr9kLrMjRqMaf+MIwDSTDR+n6pM2QSHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
